### ISSUE TITLE
dead link to keybindings

### ISSUE THREAD

**Issue by treaki** [uzbl/uzbl-website#9]
Hi,

on the faq page ( http://www.uzbl.org/faq.php ) is a link to the keybindings page which leads to 404 ( http://uzbl.org/keybindings.php ), please fix that.

regards

**Comment by mathstuf** [comment]
It needs a revisit anyways. Related to uzbl/uzbl#240. Thanks for the report.

**Comment by qguv** [comment]
Googlers: The page has been dead [since February](https://github.com/uzbl/uzbl-website/commit/5ae9e0ae4aeffee18faae6c3802cd490becd2b8a#diff-828e0013b8f3bc1bb22b4f57172b019dL13), but there's [a mirror of the page](http://web.archive.org/web/20160126193854/http://uzbl.org/keybindings.php) available.

@mathstuf It's difficult to start using uzbl without some keybindings cheatsheet. If a patch were accepted [upstream](https://github.com/uzbl/uzbl) to create a new page `KEYBINDINGS.md` in [docs](https://github.com/uzbl/uzbl/tree/master/docs) in the same style as the old one, updated to the newest keybindings in a clean `~/.config/uzbl/config`, would you accept a PR to replace the dead links to the old `keybindings.php` to this new page?

**Comment by mathstuf** [comment]
I'd accept a `KEYBINDINGS.md` file. However, for the website @barrucadu is the maintainer since he hosts it. I'm sure a PR to change a link will be fine though.

**Comment by qguv** [comment]
I've written [a PR in uzbl/uzbl](https://github.com/uzbl/uzbl/pull/296) for new keybindings documentation. I have [a commit ready](https://github.com/qguv/uzbl-website/commit/46cbf9dbf92b95616944e32cb96ad05bca389d86) that will restore the keybindings page once uzbl/uzbl merges the PR.

**Comment by keis** [comment]
Pushed the fix to master. I think there is a automatic build that will eventually take that live.

**Comment by keis** [comment]
Thanks @qguv :)
